pipeline {
    agent any

    stages {
        stage('choose tag') {
            steps {
                script {
                    sshagent(credentials : ['metech-ssh']) {
                        def filesList = sh (script: "ssh -o StrictHostKeyChecking=no -l jenkins_tech 195.93.252.91 'ls ./nexus'", returnStdout: true).trim()
                        env.jarName = input message: 'jars',
                            parameters: [choice(choices: "${filesList}", name: '')]
                     }
                }
            }
        }

        stage('stop') {
            steps {
                sshagent(credentials : ['metech-ssh']) {
                    sh "ssh -o StrictHostKeyChecking=no -l jenkins_tech 195.93.252.91 'cd link-shortener && docker compose down'"
                }
            }
        }

        stage('prepare') {
            steps {
                sshagent(credentials : ['metech-ssh']) {
                    sh "ssh -o StrictHostKeyChecking=no -l jenkins_tech 195.93.252.91 'rm -r ./link-shortener/*'"
                    sh "ssh -o StrictHostKeyChecking=no -l jenkins_tech 195.93.252.91 'cp ./nexus/${jarName}.jar ./link-shortener/link-shortener.jar'"
                    sh "scp -o StrictHostKeyChecking=no ./release/deploy/docker-compose.yaml jenkins_tech@195.93.252.91:./link-shortener/docker-compose.yaml"
                    sh "scp -o StrictHostKeyChecking=no ./release/deploy/Dockerfile jenkins_tech@195.93.252.91:./link-shortener/Dockerfile"
                }
            }
        }

        stage('deploy') {
            steps {
                sshagent(credentials : ['metech-ssh']) {
                    sh "ssh -o StrictHostKeyChecking=no -l jenkins_tech 195.93.252.91 'cd link-shortener && docker compose up -d --build'"
                }
            }
        }


        // шаги:
        // остановить предыдущую сборку
        // скопировать докерфайл и докер компоуз
        // добавить внешние конфиги
    }
}